data_source:
    directory: 'data/raw/'
    file_name: aqms_raw_data_2.csv
    data_column: 'MESSAGE'
    columns: ['id_sensor', 'datetime', 'pm1', 'pm25', 'pm10', 'co', 'temperature', 'humidity', 'pressure']

    datetime_feature: 'datetime'
    num_features: ['id_sensor', 'pm1', 'pm25', 'pm10', 'co', 'temperature', 'humidity', 'pressure']
    int_features: ['id_sensor', 'pm1', 'pm25', 'pm10']
    float_features: ['co', 'temperature', 'humidity', 'pressure']
    
    data_to_remove: [1002, 3498, 3399, 6546, 6548, 6549, 6551, 6552, 6553, 93274]
    # data_to_remove: [1002, 3498, 3399, 6546, 6548, 6549, 6551, 6552, 6553, 93274, 105453, 105454, 105455, 105793, 105794, 107301, 107302, 107304, 107437, 107438, 108637, 108638, 108641]
    id_sensor: 'id_sensor'
    sensor: [1, 2, 3]


train_test_data:
    directory: 'data/processed/'
    file_name_pkl: aqms_data_2.pkl
    file_name_csv: aqms_data_2.csv


data_mapping:
    id_sensor: 'ID'
    dateTime: 'dateTime'
    date: 'date'
    time: 'time'
    
    sensor: 'sensor'

    ZH03B: 'ZH03B'
    pm1: 'PM1.0'
    pm25: 'PM2.5'
    pm10: 'PM10.0'

    MQ7: 'MQ7'
    co: 'PPM'

    DHT22: 'DHT22'
    temperature: 'Temperature'
    humidity: 'Humidity'

    BME280: 'BME280'
    pressure: 'Pressure'    
